/* GENERATED by mkserver.py from engine.js — do not edit.
   Same economy code the browser runs, as an ES module. */

/* CEO — economy engine (JS port of ceo_engine.py).
   Practice level uses the solo path: no shocks, no rivals, exact forecast. */

const C = {
  ELASTICITY: 2.0,
  VALUE_REF: 100.0,
  QUALITY_REACH: 0.60,
  QUALITY_DECAY: 0.04,
  RD_K: 1.5,
  RD_DELAY: 2,
  UNIT_COST0: 45.0,
  LEARN_REF: 2000.0,
  LEARN_EXP: -0.12,
  LEARN_FLOOR: 0.60,
  HOLDING: 0.22,
  OBSOLESCENCE: 0.10,
  SALVAGE: 0.40,
  STOCKOUT_PEN: 0.90,
  PRODUCT_FIXED: 40000.0,
  CORP_FIXED: 25000.0,
  CORP_SCALING: 1.30,
  CAPACITY0: 2200.0,
  CAPEX_PER_UNIT: 18.0,
  CAPACITY_UPKEEP: 5.0,
  CAPACITY_RESALE: 0.40,
  CAPACITY_FLOOR: 400.0,
  RD_K_PROC: 1.5,
  EFFICIENCY_DECAY: 0.02,
  EFFICIENCY_FLOOR: 0.55,
  THROUGHPUT_EXP: 0.50,
  LAUNCH_COST: 180000.0,
  MAX_PRODUCTS: 3,           // more than three lines is bookkeeping, not strategy
  /* A second line from an established company is not a startup's product. It
     carries the firm's accumulated know-how, which is both realistic and the only
     thing that makes launching survivable: a fresh product at quality 100 against
     incumbents at 130 cannot get share, for exactly the reason a new entrant
     cannot (§17). Unlike a raw quality gift to an outsider, this scales with the
     launcher — a strong company's second line starts strong, a weak one's does
     not — so it does not have the "no setting in between" problem. */
  /* A launch must leave enough credit behind to survive the ramp. Without this the
     affordability test passed on paper and killed the company two rounds later:
     it would let a firm borrow most of its line to launch, then meet a ramp round
     that costs ~$87,000 more than the one before it with nothing left to draw. */
  LAUNCH_RESERVE: 135000.0,
  LINE_QUALITY_INHERIT: 0.85,
  LINE_EFFICIENCY_INHERIT: 0.90,
  MARKET_BASE: 2000.0,
  MATURITY_ROUND: 8,
  DECLINE: 0.08,
  RAMP: [0.65, 0.90],
  CREDIT_LIMIT: 200000.0,
  /* Borrowing is priced on how healthy the company looks, the way it is in the
     real market. As of August 2026 investment-grade paper trades around 1% over
     treasuries, all high yield around 2.7%, and CCC-and-lower at 10.2% — roughly
     a tenfold span from sound to distressed. These numbers reproduce that shape
     around the flat 5% the economy was originally balanced at. */
  INTEREST: 0.05,            // retained: the rate a debt-free company would pay
  RATE_BASE: 0.04,           // a company with no debt and profits behind it
  RATE_LEVERAGE: 0.10,       // ...rising with how much of the credit line is used
  RATE_LEVERAGE_EXP: 1.40,   // slowly at first, then quickly
  RATE_LOSSES: 0.05,         // ...and again if the business is losing money
  RATE_LOSS_REF: 80000.0,    // a loss this size counts as fully impaired
  RATE_LOSS_FLOOR: 0.20,     // ...but losses only bite in proportion to what is owed
  RATE_MAX: 0.22,            // the point past which nobody would lend at all
  RESTRUCTURE: 20000.0,
  /* --- shared market (Level 3) --- */
  SHARE_BETA: 2.3,        // share sensitivity to value-for-money
  QUALITY_PULL: 3.2,      // ...and to raw quality
  AD_GAMMA: 0.8,          // ...and to awareness
  CATEGORY_ELAST: 0.8,    // cheap prices barely grow the category; they steal share
  AD_K: 8.0,
  AD_DECAY: 0.55,         // awareness is rented, not owned
  AD_AWARE_CAP: 80.0,
  /* --- what happens when a company leaves the market --- */
  INHERIT_SHARE: 0.65,     // only this much of its demand finds a new home
  INHERIT_DECAY: 0.30,     // and the advantage fades this fast
  INHERIT_AFFINITY: 12.0,  // customers go to whoever is priced closest to what they lost
};

/* ==================== what kind of thing you make ====================
   Every constant above describes a manufactured physical good: materials in each
   unit, a factory that costs money standing idle, a warehouse, stock that rots,
   and a learning curve. That is one kind of business, not all of them. Software
   has no factory and nothing to warehouse but expensive people and a short shelf
   life; a commodity is quick and cheap and cannot be innovated into a premium;
   deep tech costs more of everything and pays back only if the research lands.

   These are multipliers on the baseline, so `hardware` is exactly the economy
   every figure in the design doc was measured against — nothing already balanced
   moves. A company always starts with a hardware product; the kind is chosen when
   launching a new line. */

const KINDS = {
  hardware: {
    label: 'Hardware',
    blurb: 'Materials in every unit and a factory to build them. Gets cheaper the more you make.',
    launch: 1.00, fixed: 1.00, unitCost: 1.00, learn: 1.00,
    capacity: 1.00, upkeep: 1.00, inventory: 1.00,
    rdLeverage: 1.00, rdDelay: 0, decay: 1.00,
  },
  software: {
    label: 'Software',
    blurb: 'No factory, nothing to warehouse, almost nothing per copy — but the people cost a fortune and it goes stale fast.',
    launch: 1.00, fixed: 1.75, unitCost: 0.09, learn: 0.15,
    capacity: 3.00, upkeep: 0.20, inventory: 0.00,
    rdLeverage: 1.15, rdDelay: 0, decay: 1.60,
  },
  commodity: {
    label: 'Commodity',
    blurb: 'Cheap and quick to start. Thin margins, and research barely moves it.',
    launch: 0.39, fixed: 0.65, unitCost: 0.62, learn: 1.00,
    capacity: 0.80, upkeep: 0.90, inventory: 1.00,
    rdLeverage: 0.45, rdDelay: 0, decay: 0.70,
  },
  deeptech: {
    label: 'Deep tech',
    blurb: 'Slow, dear and complicated to build — but research compounds hard once it lands.',
    launch: 1.15, fixed: 1.38, unitCost: 1.15, learn: 1.00,
    capacity: 1.00, upkeep: 1.00, inventory: 1.00,
    rdLeverage: 1.70, rdDelay: 1, decay: 1.00,
  },
};

const kindOf = (p) => KINDS[(p && p.kind) || 'hardware'] || KINDS.hardware;
const launchCostOf = (kind) => C.LAUNCH_COST * (KINDS[kind] || KINDS.hardware).launch;

let _pid = 0;
function newProduct(name, kind) {
  return {
    id: ++_pid,
    name,
    quality: 100.0,
    age: 0,
    inventory: 0.0,
    invBook: 0.0,
    cumUnits: C.LEARN_REF,
    kind: KINDS[kind] ? kind : 'hardware',
    capacity: C.CAPACITY0 * (KINDS[kind] || KINDS.hardware).capacity,
    alive: true,
    efficiency: 100.0,   // higher = cheaper to build and more output per plant
    awareness: 0.0,      // advertising stock: pulls SHARE, never demand
    inherited: 0.0,      // customers picked up from a company that left
    rdPipeline: [],      // {lands, dq, spend}
    procPipeline: [],    // {lands, de, spend}
    pendingCapacity: 0.0,
    stockoutLast: false,
    profitHistory: [],
  };
}

function newFirm(cash) {
  return { cash: cash === undefined ? 250000.0 : cash, debt: 0.0, products: [],
           bankrupt: false, profitHistory: [] };
}

const live = (firm) => firm.products.filter((p) => p.alive);

/* What this company pays to borrow, and what to call it.

   Two things move it, and both are things a player can see coming: how much of
   the credit line is already drawn, and whether the business behind the debt is
   making money. Leverage is superlinear — the first quarter of the line is nearly
   free, the last quarter is punishing — which is what makes borrowing early to
   fund something that pays off a genuinely different decision from borrowing late
   to cover a loss. */
function creditRate(firm, creditLimit) {
  const limit = creditLimit === undefined ? C.CREDIT_LIMIT : creditLimit;
  const lev = Math.max(0, Math.min(1, firm.debt / Math.max(1, limit)));
  const hist = firm.profitHistory || [];
  const recent = hist.slice(-3);
  const avg = recent.length ? recent.reduce((a, b) => a + b, 0) / recent.length : 0;
  const impaired = avg < 0 ? Math.min(1, -avg / C.RATE_LOSS_REF) : 0;
  /* Losses are charged in proportion to how much is already drawn. A lender
     prices your ability to repay what you owe — and a company that owes nothing
     is not distressed no matter how its quarter went. Without this, a brand new
     company was rated Stretched in round one purely for the ordinary cost of
     starting up. */
  const exposure = Math.min(1, C.RATE_LOSS_FLOOR + lev);
  const rate = C.RATE_BASE
    + C.RATE_LEVERAGE * Math.pow(lev, C.RATE_LEVERAGE_EXP)
    + C.RATE_LOSSES * impaired * exposure;
  return Math.min(C.RATE_MAX, rate);
}

/* Plain language for the same thing. Players should not have to learn a ratings
   scale to understand that the bank has gone cold on them. */
function creditStanding(firm, creditLimit) {
  const r = creditRate(firm, creditLimit);
  if (r < 0.055) return { label: 'Strong', note: 'Lenders like the look of you.' };
  if (r < 0.080) return { label: 'Sound', note: 'Normal terms.' };
  if (r < 0.115) return { label: 'Stretched', note: 'Borrowing is getting expensive.' };
  if (r < 0.160) return { label: 'Strained', note: 'The bank is charging you for the risk.' };
  return { label: 'Distressed', note: 'You are paying penalty rates on every dollar owed.' };
}

const value = (p) => C.VALUE_REF * (p.quality / 100.0);

function unitCost(p, costShock) {
  const shock = costShock === undefined ? 1.0 : costShock;
  const k = kindOf(p);
  const f = Math.max(C.LEARN_FLOOR, Math.pow(p.cumUnits / C.LEARN_REF, C.LEARN_EXP * k.learn));
  const eff = Math.max(C.EFFICIENCY_FLOOR, 100.0 / Math.max(p.efficiency, 1.0));
  return C.UNIT_COST0 * k.unitCost * f * eff * shock;
}

/* Process R&D raises throughput as well as cutting cost, so it is a genuine
   alternative to buying more plant. */
function effCapacity(p) {
  return p.capacity * Math.pow(p.efficiency / 100.0, C.THROUGHPUT_EXP);
}

function demandPool(p, marketMult) {
  const mm = marketMult === undefined ? 1.0 : marketMult;
  const ramp = p.age < C.RAMP.length ? C.RAMP[p.age] : 1.0;
  let decline = 1.0;
  if (p.age >= C.MATURITY_ROUND) {
    decline = Math.pow(1 - C.DECLINE, p.age - C.MATURITY_ROUND + 1);
  }
  const reach = Math.pow(p.quality / 100.0, C.QUALITY_REACH);
  let pool = (C.MARKET_BASE + p.inherited) * ramp * decline * reach * mm;
  if (p.stockoutLast) pool *= C.STOCKOUT_PEN;
  return pool;
}

const priceMultiplier = (price, val) =>
  Math.max(0.0, 1 + C.ELASTICITY * (1 - price / val));

const soloDemand = (p, price, marketMult) =>
  demandPool(p, marketMult) * priceMultiplier(price, value(p));

/* ---------------- PHASE A ---------------- */
function upkeep(firm, roundNo) {
  const landed = [];
  for (const p of live(firm)) {
    const due = p.rdPipeline.filter((r) => r.lands <= roundNo);
    const gain = due.reduce((a, r) => a + r.dq, 0);
    if (gain > 0) landed.push({ product: p.name, gain });
    p.quality += gain;
    p.rdPipeline = p.rdPipeline.filter((r) => r.lands > roundNo);
    const dueP = p.procPipeline.filter((r) => r.lands <= roundNo);
    const gainE = dueP.reduce((a, r) => a + r.de, 0);
    if (gainE > 0) landed.push({ product: p.name, efficiency: gainE });
    p.efficiency += gainE;
    p.procPipeline = p.procPipeline.filter((r) => r.lands > roundNo);
    const capAdded = p.pendingCapacity;
    p.capacity += p.pendingCapacity;
    p.pendingCapacity = 0.0;
    if (capAdded > 0) landed.push({ product: p.name, capacity: capAdded });
    p.quality *= 1 - C.QUALITY_DECAY * kindOf(p).decay;
    p.efficiency *= 1 - C.EFFICIENCY_DECAY;
    p.awareness *= 1 - C.AD_DECAY;
    p.inherited *= 1 - C.INHERIT_DECAY;
    p.invBook *= 1 - C.OBSOLESCENCE * kindOf(p).inventory;
  }
  return landed;
}

/* Advertising buys awareness the same round it is spent, and awareness feeds
   SHARE — so in a shared market it has to land before demand is split. The caller
   runs this for every firm first, which keeps the ordering identical to Python. */
function applyAdvertising(firm, decisions) {
  for (const p of live(firm)) {
    const ad = (decisions[p.name] || {}).advertising || 0;
    if (ad > 0) {
      p.awareness = Math.min(C.AD_AWARE_CAP,
        p.awareness + C.AD_K * Math.sqrt(ad / 1000.0));
    }
  }
}

/* When a company leaves, its customers do not evaporate — but neither do they all
   find a new supplier. About two thirds land somewhere; the rest simply stop
   buying, because nobody has the capacity or the proposition to serve them. And
   they go to the closest substitute, not the biggest survivor: when Spirit failed,
   its traffic went to JetBlue, Breeze, Frontier and Allegiant, and none of it went
   to the legacy carriers. */
function distributeCustomers(leaver, survivors, leaverPrice, prices) {
  const orphaned = live(leaver).reduce((a, p) => a + C.MARKET_BASE + p.inherited, 0)
                 * C.INHERIT_SHARE;
  const pool = [];
  for (const f of survivors) if (!f.bankrupt) for (const p of live(f)) pool.push(p);
  if (!pool.length || orphaned <= 0) return { orphaned: 0, shares: [] };
  const affinity = (p) => {
    if (leaverPrice === undefined || !prices || prices[p.name] === undefined) return 1;
    const gap = Math.abs(Math.log(Math.max(prices[p.name], 1e-6) / Math.max(leaverPrice, 1e-6)));
    return Math.exp(-C.INHERIT_AFFINITY * gap);
  };
  const weights = pool.map((p) => demandPool(p) * affinity(p));
  const total = weights.reduce((a, b) => a + b, 0) || pool.length;
  const shares = [];
  pool.forEach((p, i) => {
    const got = orphaned * (weights[i] / total);
    p.inherited += got;
    shares.push({ product: p, units: got, fraction: weights[i] / total });
  });
  return { orphaned, shares };
}

/* ---------------- shared market ---------------- */
/* entries: [{product, price}] across every firm. Three kinds of buyer. */
function sharedDemands(entries, marketMult) {
  const mm = marketMult === undefined ? 1 : marketMult;
  const vbar = entries.reduce((a, e) => a + value(e.product), 0) / Math.max(1, entries.length);
  const attr = entries.map((e) => e.price > 0
    ? Math.pow(value(e.product) / e.price, C.SHARE_BETA)
      * Math.pow(value(e.product) / vbar, C.QUALITY_PULL)
      * Math.pow(1 + e.product.awareness / 100, C.AD_GAMMA)
    : 0);
  const tot = attr.reduce((a, b) => a + b, 0) || 1;
  const shares = attr.map((a) => a / tot);
  const pbar = entries.reduce((a, e, i) => a + e.price * shares[i], 0);
  const vbarW = entries.reduce((a, e, i) => a + value(e.product) * shares[i], 0);
  const pool = entries.reduce((a, e) => a + demandPool(e.product, mm), 0);
  const total = pool * Math.max(0, 1 + C.CATEGORY_ELAST * (1 - pbar / vbarW));
  return { demands: shares.map((s) => total * s), shares };
}

/* Demand a firm cannot fill spills to rivals that still have stock. */
function spill(demands, availables) {
  const n = demands.length;
  const sales = new Array(n).fill(0);
  const remD = demands.slice();
  const remA = availables.slice();
  for (let pass = 0; pass < 5; pass++) {
    let unmet = 0;
    for (let i = 0; i < n; i++) {
      const take = Math.min(remD[i], remA[i]);
      sales[i] += take; remA[i] -= take; unmet += remD[i] - take; remD[i] = 0;
    }
    if (unmet <= 1e-6) break;
    const spare = remA.map((a) => Math.max(0, a));
    const tot = spare.reduce((a, b) => a + b, 0);
    if (tot <= 1e-6) break;
    for (let i = 0; i < n; i++) remD[i] = unmet * (spare[i] / tot);
  }
  return sales;
}

/* ---------------- PHASE C ---------------- */
function resolve(firm, decisions, roundNo, opts) {
  const o = opts || {};
  const marketMult = o.marketMult === undefined ? 1.0 : o.marketMult;
  const costShock = o.costShock === undefined ? 1.0 : o.costShock;
  const capacityMult = o.capacityMult === undefined ? 1.0 : o.capacityMult;

  let revenue = 0.0, costs = 0.0;
  const log = [];
  const liveList = live(firm);

  /* In a shared market the caller has already split demand between firms and
     passes each firm its slice. Only compute demand here when playing solo. */
  const demands = {};
  for (const p of liveList) {
    demands[p.name] = (o.sharedDemands && o.sharedDemands[p.name] !== undefined)
      ? o.sharedDemands[p.name]
      : soloDemand(p, decisions[p.name].price, marketMult);
  }

  const availables = {};
  const unitCosts = {};
  for (const p of liveList) {
    const d = decisions[p.name];
    if (d.discontinue) continue;
    const sell = Math.min(Math.max(0.0, d.sellCapacity || 0.0),
                          Math.max(0.0, p.capacity - C.CAPACITY_FLOOR));
    if (sell > 0) { p.capacity -= sell; d._soldCapacity = sell; }
    const produce = Math.max(0.0, Math.min(d.produce, effCapacity(p) * capacityMult));
    const uc = unitCost(p, costShock);
    unitCosts[p.name] = uc;
    costs += produce * uc;
    p.cumUnits += produce;
    p.invBook += produce * uc;
    availables[p.name] = p.inventory + produce;
    d._produced = produce;
  }

  for (const p of liveList) {
    const d = decisions[p.name];
    if (d.discontinue) {
      costs += C.RESTRUCTURE;
      revenue += p.invBook * C.SALVAGE;
      log.push({
        name: p.name, event: 'discontinued', profit: 0,
        salvage: p.invBook * C.SALVAGE, restructure: C.RESTRUCTURE,
      });
      p.alive = false;
      p.inventory = 0.0;
      p.invBook = 0.0;
      continue;
    }

    const available = availables[p.name];
    const demand = demands[p.name];
    const sales = Math.min(demand, available);
    p.stockoutLast = demand > available + 1e-6;
    const unitBook = available > 0 ? p.invBook / available : 0.0;
    const cogs = sales * unitBook;
    p.inventory = available - sales;
    p.invBook = p.inventory * unitBook;
    revenue += sales * d.price;
    const pk = kindOf(p);
    const holding = p.invBook * C.HOLDING * pk.inventory;
    const upkeepCost = p.capacity * C.CAPACITY_UPKEEP * pk.upkeep;
    const rd = d.rd || 0.0;
    const rdProcess = d.rdProcess || 0.0;
    const advertising = d.advertising || 0.0;
    const capex = d.capex || 0.0;
    costs += holding + upkeepCost + C.PRODUCT_FIXED * pk.fixed + rd + rdProcess + advertising + capex;

    const sold = d._soldCapacity || 0.0;
    if (sold > 0) revenue += sold * C.CAPEX_PER_UNIT * C.CAPACITY_RESALE;
    if (rd > 0) {
      const dq = C.RD_K * pk.rdLeverage * Math.sqrt(rd / 1000.0) * (100.0 / Math.max(p.quality, 1));
      p.rdPipeline.push({ lands: roundNo + C.RD_DELAY + pk.rdDelay, dq, spend: rd });
    }
    if (rdProcess > 0) {
      const de = C.RD_K_PROC * Math.sqrt(rdProcess / 1000.0)
               * (100.0 / Math.max(p.efficiency, 1));
      p.procPipeline.push({ lands: roundNo + C.RD_DELAY + pk.rdDelay, de, spend: rdProcess });
    }
    if (capex > 0) p.pendingCapacity += capex / C.CAPEX_PER_UNIT;

    p.age += 1;
    const pprofit = sales * d.price - cogs - holding - upkeepCost
                  - C.PRODUCT_FIXED * pk.fixed - rd - rdProcess - advertising;
    p.profitHistory.push(pprofit);
    log.push({
      name: p.name, demand, sales, produced: d._produced,
      inventory: p.inventory, profit: pprofit, stockout: p.stockoutLast,
      revenue: sales * d.price, cogs, holding, upkeepCost, rd, capex,
      unitCost: unitCosts[p.name], lostSales: Math.max(0, demand - available),
    });
  }

  const corp = C.CORP_FIXED * Math.pow(Math.max(1, liveList.length), C.CORP_SCALING);
  costs += corp;
  /* Priced on last round's standing, not this one's — you borrow at the rate you
     had earned, and the consequences of a bad round land the round after. */
  const rate = creditRate(firm, o.creditLimit);
  const interest = firm.debt * rate;
  costs += interest;
  const profit = revenue - costs;
  firm.profitHistory.push(profit);
  if (firm.profitHistory.length > 8) firm.profitHistory.shift();
  firm.cash += profit;
  if (firm.cash < 0) {
    firm.debt += -firm.cash;
    firm.cash = 0.0;
  } else if (firm.debt > 0) {
    const pay = Math.min(firm.cash, firm.debt);
    firm.debt -= pay;
    firm.cash -= pay;
  }
  /* Live sessions let the host pick a difficulty preset, which moves the credit
     limit. Defaults to the balanced constant when nothing is passed. */
  const creditLimit = o.creditLimit === undefined ? C.CREDIT_LIMIT : o.creditLimit;
  if (firm.debt > creditLimit) firm.bankrupt = true;
  return { profit, log, corp, interest, rate, revenue, costs };
}

function companyValue(firm) {
  let v = firm.cash - firm.debt;
  for (const p of firm.products) {
    v += p.invBook * C.SALVAGE;
    if (p.alive && p.profitHistory.length) {
      const recent = p.profitHistory.slice(-3);
      const avg = recent.reduce((a, b) => a + b, 0) / recent.length;
      if (avg > 0) v += 4 * avg;
    }
  }
  return v;
}



/* ==================== shock deck (Level 2) ====================
   Three independent tracks, so a recession and a cost spike can bite at once.
   Headlines describe what is happening NOW — they are narration, not prediction.
   Measured testing showed leading indicators are worth ~3% even when perfectly
   reliable, so this deliberately does not forecast. */

const SHOCKS = {
  demand: [
    { name: 'Recession', mult: 0.70, dur: 3,
      start: 'Recession declared as output falls for a second quarter',
      during: 'Recession — households have stopped spending',
      end: 'Forecasters call the recession over' },
    { name: 'Consumer boom', mult: 1.30, dur: 2,
      start: 'Spending surges as consumer confidence hits a five-year high',
      during: 'Consumer boom — buyers are out in force',
      end: 'The spending surge cools off' },
    { name: 'Category trend', mult: 1.25, dur: 3,
      start: 'Your category is suddenly fashionable, say retail analysts',
      during: 'Category in vogue — new buyers keep arriving',
      end: 'The trend moves on to something else' },
    { name: 'Demand slump', mult: 0.80, dur: 2,
      start: 'Retailers report a sharp slowdown at the checkout',
      during: 'Slump — the shops are quiet',
      end: 'Retail traffic returns to normal' },
  ],
  cost: [
    { name: 'Input cost spike', mult: 1.35, dur: 2,
      start: 'Component prices jump after a supplier fire',
      during: 'Input costs are up sharply — every unit is dearer to make',
      end: 'Component prices settle back down' },
    { name: 'Tariffs', mult: 1.20, dur: 3,
      start: 'New tariffs announced on imported parts',
      during: 'Tariffs in force — parts cost more',
      end: 'Tariffs lifted after trade talks' },
    { name: 'Commodity glut', mult: 0.85, dur: 2,
      start: 'Oversupply sends raw material prices tumbling',
      during: 'Cheap materials — your units cost less to build',
      end: 'Material prices normalise' },
  ],
  capacity: [
    { name: 'Supply crunch', mult: 0.65, dur: 2,
      start: 'Port strike halts inbound shipments',
      during: 'Supply crunch — you cannot run the factory at full tilt',
      end: 'The ports reopen' },
    { name: 'Logistics strike', mult: 0.75, dur: 2,
      start: 'Hauliers walk out over pay',
      during: 'Haulage disrupted — output is constrained',
      end: 'Hauliers return to work' },
  ],
};
const SHOCK_CHANCE = { demand: 0.20, cost: 0.16, capacity: 0.12 };
const TECH_LEAP_CHANCE = 0.08;
const TECH_LEAP_HIT = 0.88;

/* Small seeded PRNG so a game can be replayed from its seed. */
function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/* The shock stream has to survive being written to storage and read back in a
   different process, so the state is a seed and a call count rather than a live
   generator — JSON cannot hold a closure. Rebuilding costs one cheap loop and the
   count stays in the low hundreds over a whole game. */
function newShockState(seed) {
  return { seed: seed >>> 0, calls: 0, active: {}, news: [] };
}

function shockRand(S) {
  if (typeof S.rand !== 'function' || S.at !== S.calls) {
    const r = mulberry32(S.seed);
    for (let i = 0; i < S.calls; i++) r();
    S.rand = r;
  }
  const v = S.rand();
  S.calls += 1;
  S.at = S.calls;
  return v;
}

/* Called at the top of each round, before the player decides. */
/* `firms` may be one firm or many. A technology leap raises the bar for everyone
   in the market — passing a single firm made it hit that company alone, which in
   a shared market means one player is randomly punished and the rest are not. */
function shockTick(S, firms) {
  S.news = [];
  for (const track of Object.keys(SHOCKS)) {
    const cur = S.active[track];
    if (cur && cur.left > 1) {
      cur.left -= 1;
      S.news.push({ kind: 'during', track, text: cur.card.during, card: cur.card });
    } else if (cur) {
      S.news.push({ kind: 'end', track, text: cur.card.end, card: cur.card });
      delete S.active[track];
    } else if (shockRand(S) < SHOCK_CHANCE[track]) {
      const deck = SHOCKS[track];
      const card = deck[Math.floor(shockRand(S) * deck.length)];
      S.active[track] = { card, left: card.dur };
      S.news.push({ kind: 'start', track, text: card.start, card });
    }
  }
  const hit = Array.isArray(firms) ? firms : (firms ? [firms] : []);
  if (shockRand(S) < TECH_LEAP_CHANCE && hit.length) {
    for (const f of hit) for (const p of live(f)) p.quality *= TECH_LEAP_HIT;
    S.news.push({ kind: 'start', track: 'tech',
      text: 'A new generation of products arrives — the bar for "good" just rose',
      card: { name: 'Technology leap' } });
  }
  return S.news;
}

const shockMult = (S, track) => (S.active[track] ? S.active[track].card.mult : 1.0);



/* ==================== bot opponents (Level 3) ====================
   Personalities are the five configurations measured in simulation. They are
   fixed rather than adaptive: the balance numbers were obtained with these
   exact values, and a bot that improvises would invalidate them. */

const BOTS = [
  { id: 'discounter', name: 'Valu-Line', tagline: 'Cheap and everywhere',
    strategy: 'Discounter — undercut and win on volume',
    blurb: 'Undercuts on price and makes it up on volume. Spends most of its research on cutting costs.',
    priceRatio: 0.92, produceRatio: 1.18, rdTotal: 58000, procShare: 0.30, headroom: 1.05, ad: 12000 },
  { id: 'premium', name: 'Meridian', tagline: 'The best thing on the shelf',
    strategy: 'Premium — charge more, out-innovate',
    blurb: 'Charges the most and earns it — nearly all research goes into the product. Buys little advertising.',
    priceRatio: 1.04, produceRatio: 1.05, rdTotal: 68000, procShare: 0.05, headroom: 1.00, ad: 9000 },
  { id: 'marketer', name: 'Brightwell', tagline: 'You have heard of them',
    strategy: 'Marketer — buy attention',
    blurb: 'Outspends everyone on advertising. Watch what that does to its balance sheet before you copy it.',
    priceRatio: 0.99, produceRatio: 1.10, rdTotal: 58000, procShare: 0.15, headroom: 1.00, ad: 15000 },
  { id: 'operator', name: 'Kestrel Works', tagline: 'Lean and quiet',
    strategy: 'Operator — small plant, low unit costs',
    blurb: 'Runs a small plant at full tilt and grinds its unit costs down. Rarely spectacular, rarely in trouble.',
    priceRatio: 0.96, produceRatio: 1.12, rdTotal: 60000, procShare: 0.28, headroom: 0.95, ad: 10000 },
  { id: 'balanced', name: 'Harbour & Co', tagline: 'Middle of everything',
    strategy: 'Balanced — no strong opinions',
    blurb: 'No strong opinions. Prices near value, splits research sensibly, advertises moderately.',
    priceRatio: 0.98, produceRatio: 1.10, rdTotal: 60000, procShare: 0.15, headroom: 1.00, ad: 12000 },
];

/* ---------------- seating: labelled vs hidden ----------------
   The behaviour layer below removes the tells a player could measure. This layer
   removes the ones they could simply read. In a labelled game the personalities
   are the teaching material and keep their names and taglines. In a hidden game
   a tagline is a perfect identity leak — "Cheap and everywhere" is a confession —
   so names come from the same pool human players draw from, taglines vanish, and
   the personalities are shuffled so seat order carries no information either. */

const NAME_POOL = [
  'Northgate', 'Aster Industries', 'Bellweather', 'Corvid Manufacturing', 'Dunmore & Sons',
  'Elder Row', 'Fairhaven Works', 'Granby Supply', 'Halloway', 'Ironvale',
  'Juniper Trading', 'Kepler Goods', 'Larkfield', 'Mercer Brothers', 'Nine Elms',
  'Osprey Works', 'Pemberton', 'Quarry Lane', 'Redhill Manufacturing', 'Stanmore',
  'Thackeray', 'Uplands Co', 'Vance & Hart', 'Westmere', 'Yarrow Industries',
];

function shuffle(arr, rnd) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rnd() * (i + 1));
    const t = a[i]; a[i] = a[j]; a[j] = t;
  }
  return a;
}

/* Returns the rival seats for a game: which personality sits where, what it is
   called, and what — if anything — the player is told about it. */
function seatRivals(seed, n, hidden) {
  const rnd = mulberry32(seed ^ 0x5eaf1);
  const count = Math.max(1, Math.min(n, BOTS.length));
  const picked = hidden ? shuffle(BOTS, rnd).slice(0, count) : BOTS.slice(0, count);
  const names = hidden ? shuffle(NAME_POOL, rnd) : null;
  return picked.map((bot, i) => ({
    bot,
    label: hidden ? names[i] : bot.name,
    tagline: hidden ? '' : bot.tagline,
    blurb: hidden ? '' : bot.blurb,
    isBot: true,
  }));
}

/* ---------------- making a bot hard to spot ----------------
   A player only ever sees a rival's price, quality and share — so price is where
   essentially all the detection risk lives. The giveaway was never that a bot's
   price stayed still (it moves, because value moves); it was the DECIMALS. A fixed
   ratio times a computed value emits $106.59 every round forever. People type $105. */

function newBotState(seed, bot) {
  return { rand: mulberry32(seed), drift: 0, lastShare: null,
           lastStockout: false, mistakeCd: 0, anchor: bot.priceRatio };
}

const snapTo = (x, step) => Math.round(x / step) * step;

/* A per-round variant of the personality — never a different personality. */
function humaniseBot(bot, st) {
  const rnd = st.rand;
  const u = (a, b) => a + rnd() * (b - a);
  // a slow, mean-reverting wander: nobody re-derives the same number every quarter
  st.drift += u(-0.026, 0.026);
  st.drift *= 0.84;
  // and reactions to what just happened
  if (st.lastShare !== null) {
    if (st.lastShare < 0.14) st.drift -= 0.012;        // losing badly: shade down
    else if (st.lastShare > 0.34) st.drift += 0.008;   // comfortable: take margin
  }
  if (st.lastStockout) st.drift += 0.010;              // could not supply: ease off
  st.drift = Math.max(-0.07, Math.min(0.07, st.drift));

  const out = Object.assign({}, bot);
  out.priceRatio = st.anchor + st.drift;
  out.rdTotal = Math.max(0, snapTo(bot.rdTotal * (1 + u(-0.14, 0.14)), 5000));
  out.ad = Math.max(0, snapTo(bot.ad * (1 + u(-0.18, 0.18)), 1000));
  out.produceRatio = bot.produceRatio * (1 + u(-0.05, 0.05));
  out.headroom = bot.headroom * (1 + u(-0.04, 0.04));
  out.procShare = Math.min(0.6, Math.max(0, bot.procShare + u(-0.05, 0.05)));

  // real mistakes, occasionally, with a cooldown so they do not cluster
  st.mistakeCd = Math.max(0, st.mistakeCd - 1);
  if (st.mistakeCd === 0 && rnd() < 0.09) {
    st.mistakeCd = 3;
    const kind = Math.floor(rnd() * 4);
    if (kind === 0) out.produceRatio *= 1.35;             // over-ordered
    else if (kind === 1) out.rdTotal = 0;                 // skipped research
    else if (kind === 2) out.ad = snapTo(bot.ad * 2.2, 1000);  // panic-bought attention
    else out.headroom *= 1.45;                            // overbuilt the factory
  }
  return out;
}

/* People post round prices. This is the single most visible tell. */
function humanPrice(val, ratio, rnd) {
  const raw = val * ratio;
  const roll = rnd();
  if (roll < 0.30) return Math.round(raw / 5) * 5;
  if (roll < 0.80) return Math.round(raw);
  return Math.round(raw * 2) / 2;
}

function botObserve(st, share, stockout) {
  st.lastShare = share;
  st.lastStockout = stockout;
}

/* What any firm can honestly work out before a round resolves: its own share if
   every rival repeats the price it charged last round. The bots get exactly the
   same information the human player does — nobody sees this round's prices. */
function estimateShare(me, myPrice, rivals, rivalLastPrices, marketMult) {
  const entries = [{ product: me, price: myPrice }].concat(
    rivals.map((rp, k) => ({ product: rp, price: rivalLastPrices[k] })));
  return sharedDemands(entries, marketMult).demands[0];
}

/* Per product, so a bot running two lines splits its money across them instead of
   spending its whole budget twice. */
function botDecideFor(firm, bot, p, guess, opts) {
  const o = opts || {};
  const cm = o.capacityMult === undefined ? 1 : o.capacityMult;
  const share = o.budgetShare === undefined ? 1 : o.budgetShare;
  const price = value(p) * bot.priceRatio;
  let budget = firm.cash * 0.55 * share;
  let capex = 0, sellCapacity = 0;
  const target = guess * bot.headroom;
  if (target > effCapacity(p) * 0.95) {
    capex = Math.min(Math.max(0, target - effCapacity(p)) * C.CAPEX_PER_UNIT, budget * 0.45);
    budget -= capex;
  } else if (p.age >= C.MATURITY_ROUND && effCapacity(p) > target * 1.3) {
    sellCapacity = p.capacity - target * 1.1;   // only shed plant in real decline
  }
  const advertising = Math.min(bot.ad, Math.max(0, budget)); budget -= advertising;
  const rd = Math.min(bot.rdTotal * (1 - bot.procShare), Math.max(0, budget)); budget -= rd;
  const rdProcess = Math.min(bot.rdTotal * bot.procShare, Math.max(0, budget)); budget -= rdProcess;
  const produce = Math.max(0, Math.min(guess * bot.produceRatio, effCapacity(p) * cm) - p.inventory);
  return { price, produce, rd, rdProcess, advertising, capex, sellCapacity };
}

function botDecide(firm, bot, guess, opts) {
  return botDecideFor(firm, bot, live(firm)[0], guess, opts);
}

/* A new product line for an existing company, carrying over what the company
   already knows how to do. */
function newLine(firm, name, kind) {
  const p = newProduct(name, kind);
  const best = live(firm).reduce((a, x) => Math.max(a, x.quality), 0);
  const eff = live(firm).reduce((a, x) => Math.max(a, x.efficiency), 0);
  /* Know-how carries over in full only when the new line is the same sort of
     thing. A factory's process learning is worth much less to a software product,
     and vice versa — which is what stops "launch a different kind" being a free
     reset into whichever kind is currently strongest. */
  const same = live(firm).some((x) => (x.kind || 'hardware') === (p.kind || 'hardware'));
  const carry = same ? 1 : 0.6;
  if (best > 0) p.quality = Math.max(p.quality, best * C.LINE_QUALITY_INHERIT * carry);
  if (eff > 0) p.efficiency = Math.max(p.efficiency, eff * C.LINE_EFFICIENCY_INHERIT * carry);
  return p;
}

/* Whether a bot opens a second line. Without this, long live games are decided by
   the fact that only the humans can answer a product going into decline — which
   would be a worse asymmetry than the one it fixes. The rules are the ones a
   cautious operator would use: pay cash, never while in debt, only once the
   existing line is maturing, and never so late that it cannot pay back. */
function botShouldLaunch(firm, roundNo, totalRounds, rnd, creditLimit) {
  const ps = live(firm);
  if (!ps.length || ps.length >= C.MAX_PRODUCTS) return false;
  /* Bots will borrow for a launch, but only a third of their remaining line —
     they are meant to be plausible operators, not reckless ones. */
  const headroom = Math.max(0, (creditLimit === undefined ? C.CREDIT_LIMIT : creditLimit) - firm.debt);
  if (firm.cash + headroom - C.LAUNCH_COST < C.LAUNCH_RESERVE) return false;
  if (totalRounds - roundNo < 5) return false;
  const oldest = ps.reduce((a, p) => Math.max(a, p.age), 0);
  if (oldest < C.MATURITY_ROUND - 3) return false;
  return rnd() < 0.5;
}




export {
  C,
  newProduct,
  newFirm,
  live,
  value,
  unitCost,
  effCapacity,
  demandPool,
  priceMultiplier,
  soloDemand,
  upkeep,
  resolve,
  companyValue,
  applyAdvertising,
  sharedDemands,
  spill,
  distributeCustomers,
  creditRate,
  creditStanding,
  SHOCKS,
  SHOCK_CHANCE,
  newShockState,
  shockTick,
  shockMult,
  mulberry32,
  BOTS,
  NAME_POOL,
  seatRivals,
  shuffle,
  estimateShare,
  botDecide,
  botDecideFor,
  botShouldLaunch,
  newLine,
  KINDS,
  kindOf,
  launchCostOf,
  newBotState,
  humaniseBot,
  humanPrice,
  botObserve,
};
